# Site settings
title: Project:Chroma
email: Project.Chroma.devs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chroma is a color-based 2D platformer written in Java.
  In addition, it features the ability to be extensively modified through Chromods.
baseurl: "/ProjectChroma.github.io" # the subpath of your site, e.g. /blog/
url: "https://open-sourceress.github.io" # the base hostname & protocol for your site
twitter_username: chroma_devs
github_username: ProjectChroma
source: _pages

# Build settings
markdown: kramdown
